name: Executive file generation

on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - run: ./installResources.ps1



